{{- if .Values.service }}
{{- if .Values.service.gateway }}
{{- if .Values.service.gateway.enabled }}
{{- if .Values.service.gateway.routes }}
{{- $port := .Values.service.port -}}
{{- range $key , $route := .Values.service.gateway.routes }}
---
apiVersion: getambassador.io/v1
kind:  Mapping
metadata:
  name:  {{ include "zeeqs.fullname" $ }}-{{ $key }}-mapping
spec:
{{- if $route.ambassador_id }}
  ambassador_id: {{ $route.ambassador_id }}
{{- else }}
  ambassador_id: gw-{{ $.Release.Namespace }}
{{- end }}
{{- if $route.prefix }}
  prefix: {{ $route.prefix }}
{{- else }}
  prefix: /{{ include "zeeqs.fullname" $ }}/
{{- end }}
  service: {{ include "zeeqs.fullname" $ }}.{{ $.Release.Namespace }}:{{ $port }}
{{- if $route.extra }}
{{ toYaml $route.extra | indent 2 }}
{{- end }}
{{- if $route.legacy }}
---
apiVersion: getambassador.io/v1
kind:  Mapping
metadata:
  name:  {{ include "zeeqs.fullname" $ }}-{{ $key }}-proxy-mapping
spec:
{{- if $route.ambassador_id }}
  ambassador_id: {{ $route.ambassador_id }}
{{- else }}
  ambassador_id: gw-{{ $.Release.Namespace }}
{{- end }}
{{- if $route.prefix }}
  prefix: /proxy{{ $route.prefix }}
{{- else }}
  prefix: /proxy/{{ include "zeeqs.fullname" $ }}/
{{- end }}
  service: {{ include "zeeqs.fullname" $ }}.{{ $.Release.Namespace }}:{{ $port }}
{{- if $route.extra }}
{{ toYaml $route.extra | indent 2 }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
